### 사망 신고서 등록
POST /residents/7/death
Host: localhost:8080
Content-Type: application/json

{
  "targetResidentSerialNumber": 5,
  "birthDeathReportDate": "2023-05-18",
  "reportQualificationsCode": "자",
  "emailAddress": "ohdo@kakao.com",
  "phoneNumber": "010-1234-5678"
}

### 사망 신고서 수정
PUT /residents/7/death/5
Host: localhost:8080
Content-Type: application/json

{
  "birthDeathReportDate": "2023-05-18",
  "reportQualificationsCode": "자",
  "emailAddress": "updateTest@kakao.com",
  "phoneNumber": "010-4321-8765"
}

### 사망 신고서 삭제
DELETE /residents/7/death/5
Host: localhost:8080