-- MySQL Script generated by MySQL Workbench
-- Sat May  6 01:42:09 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
USE nhn_academy_4;

-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
DROP TABLE User;
CREATE TABLE IF NOT EXISTS `User` (
                                      `user_id` INT NOT NULL,
                                      `id` VARCHAR(255) NOT NULL,
                                      `password` VARCHAR(255) NOT NULL,
                                      `name` VARCHAR(255) NOT NULL,
                                      `profile_file_name` VARCHAR(255) NULL,
                                      PRIMARY KEY (`user_id`))
    ENGINE = InnoDB;

ALTER TABLE `User`   MODIFY `user_id` BIGINT NOT NULL AUTO_INCREMENT;
-- -----------------------------------------------------
-- Table `mydb`.`post`
-- -----------------------------------------------------
DROP TABLE Post;
CREATE TABLE IF NOT EXISTS `Post` (
    `id` BIGINT NOT NULL,
    `title` VARCHAR(255) NOT NULL,
    `content` VARCHAR(255) NOT NULL,
    `writer_user_id` BIGINT NOT NULL,
    `write_time` DATETIME NOT NULL,
    `view_count` INT NOT NULL,
    PRIMARY KEY (`id`),
    INDEX `fk_post_user_idx` (`writer_user_id` ASC),
    CONSTRAINT `fk_post_user`
      FOREIGN KEY (`writer_user_id`)
          REFERENCES `User` (`user_id`)
          ON DELETE NO ACTION
          ON UPDATE NO ACTION
                                  )
    ENGINE = InnoDB;

ALTER TABLE `Post`   MODIFY `id` BIGINT NOT NULL AUTO_INCREMENT;
ALTER TABLE Post MODIFY COLUMN writer_user_id INT unsigned DEFAULT NULL;
SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT INTO Post
SET title          = 'test',
    content        = 'test',
    writer_user_id = (SELECT user_id FROM User WHERE id = 'test1'),
    write_time     = now(),
    view_count     = 0;
SELECT last_insert_id();

DELETE FROM Post WHERE id > 70;
