-- MySQL Script generated by MySQL Workbench
-- Mon May  1 03:47:56 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema flight
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `flight` ;

-- -----------------------------------------------------
-- Schema flight
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `flight` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `flight` ;

-- -----------------------------------------------------
-- Table `flight`.`airport`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `flight`.`airport` ;

CREATE TABLE IF NOT EXISTS `flight`.`airport` (
  `airport_id` INT NOT NULL,
  `IATA_code` VARCHAR(3) NOT NULL,
  `IACO_code` VARCHAR(4) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`airport_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `flight`.`ATC_Advisory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `flight`.`ATC_Advisory` ;

CREATE TABLE IF NOT EXISTS `flight`.`ATC_Advisory` (
  `ATC_call_record` VARCHAR(45) NOT NULL,
  `weather` VARCHAR(45) NOT NULL,
  `wind_speed` FLOAT NOT NULL,
  `sight` FLOAT NOT NULL,
  `side_wind` FLOAT NOT NULL,
  `departure_report` VARCHAR(45) NOT NULL,
  `airport_id` INT NOT NULL,
  PRIMARY KEY (`ATC_call_record`),
  INDEX `FK_airport_TO_ATC_Advisory_1` (`airport_id` ASC) VISIBLE,
  CONSTRAINT `FK_airport_TO_ATC_Advisory_1`
    FOREIGN KEY (`airport_id`)
    REFERENCES `flight`.`airport` (`airport_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `flight`.`customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `flight`.`customer` ;

CREATE TABLE IF NOT EXISTS `flight`.`customer` (
  `customer_no` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `cellphone` VARCHAR(13) NOT NULL,
  PRIMARY KEY (`customer_no`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `flight`.`reserved_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `flight`.`reserved_type` ;

CREATE TABLE IF NOT EXISTS `flight`.`reserved_type` (
  `reserved_type_id` INT NOT NULL,
  `reserved_type_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`reserved_type_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `flight`.`PNR`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `flight`.`PNR` ;

CREATE TABLE IF NOT EXISTS `flight`.`PNR` (
  `PNR_id` INT NOT NULL,
  `customer_no` INT NOT NULL,
  `reserved_time` DATETIME NOT NULL,
  `reserved_type_id` INT NOT NULL,
  PRIMARY KEY (`PNR_id`),
  INDEX `FK_customer_TO_PNR_1` (`customer_no` ASC) VISIBLE,
  INDEX `fk_PNR_reserved_type1_idx` (`reserved_type_id` ASC) VISIBLE,
  CONSTRAINT `FK_customer_TO_PNR_1`
    FOREIGN KEY (`customer_no`)
    REFERENCES `flight`.`customer` (`customer_no`),
  CONSTRAINT `fk_PNR_reserved_type1`
    FOREIGN KEY (`reserved_type_id`)
    REFERENCES `flight`.`reserved_type` (`reserved_type_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `flight`.`PAX`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `flight`.`PAX` ;

CREATE TABLE IF NOT EXISTS `flight`.`PAX` (
  `PAX_id` INT NOT NULL,
  `PNR_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `age` INT NOT NULL,
  `cellphone` VARCHAR(13) NOT NULL,
  PRIMARY KEY (`PAX_id`, `PNR_id`),
  INDEX `FK_PNR_TO_PAX_1` (`PNR_id` ASC) VISIBLE,
  CONSTRAINT `FK_PNR_TO_PAX_1`
    FOREIGN KEY (`PNR_id`)
    REFERENCES `flight`.`PNR` (`PNR_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `flight`.`SEG`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `flight`.`SEG` ;

CREATE TABLE IF NOT EXISTS `flight`.`SEG` (
  `SEG_id` INT NOT NULL,
  `PNR_id` INT NOT NULL,
  PRIMARY KEY (`SEG_id`, `PNR_id`),
  INDEX `FK_PNR_TO_SEG_1` (`PNR_id` ASC) VISIBLE,
  CONSTRAINT `FK_PNR_TO_SEG_1`
    FOREIGN KEY (`PNR_id`)
    REFERENCES `flight`.`PNR` (`PNR_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `flight`.`SSR_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `flight`.`SSR_type` ;

CREATE TABLE IF NOT EXISTS `flight`.`SSR_type` (
  `SSR_type_id` INT NOT NULL,
  `SSR_type_value` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`SSR_type_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `flight`.`SSR`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `flight`.`SSR` ;

CREATE TABLE IF NOT EXISTS `flight`.`SSR` (
  `SEG_id` INT NOT NULL,
  `PAX_id` INT NOT NULL,
  `SSR_type_id` INT NOT NULL,
  PRIMARY KEY (`SEG_id`, `PAX_id`),
  INDEX `FK_PAX_TO_SSR_1` (`PAX_id` ASC) VISIBLE,
  INDEX `FK_SSR_type_TO_SSR_1` (`SSR_type_id` ASC) VISIBLE,
  CONSTRAINT `FK_PAX_TO_SSR_1`
    FOREIGN KEY (`PAX_id`)
    REFERENCES `flight`.`PAX` (`PAX_id`),
  CONSTRAINT `FK_SEG_TO_SSR_1`
    FOREIGN KEY (`SEG_id`)
    REFERENCES `flight`.`SEG` (`SEG_id`),
  CONSTRAINT `FK_SSR_type_TO_SSR_1`
    FOREIGN KEY (`SSR_type_id`)
    REFERENCES `flight`.`SSR_type` (`SSR_type_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `flight`.`product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `flight`.`product` ;

CREATE TABLE IF NOT EXISTS `flight`.`product` (
  `product_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `price` INT NOT NULL,
  `explanation` VARCHAR(200) NULL DEFAULT NULL,
  PRIMARY KEY (`product_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `flight`.`accessory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `flight`.`accessory` ;

CREATE TABLE IF NOT EXISTS `flight`.`accessory` (
  `accessory_id` INT NOT NULL,
  PRIMARY KEY (`accessory_id`),
  CONSTRAINT `FK_product_TO_accessory_1`
    FOREIGN KEY (`accessory_id`)
    REFERENCES `flight`.`product` (`product_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `flight`.`affilate_product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `flight`.`affilate_product` ;

CREATE TABLE IF NOT EXISTS `flight`.`affilate_product` (
  `affilate_product_id` INT NOT NULL,
  PRIMARY KEY (`affilate_product_id`),
  CONSTRAINT `FK_product_TO_affilate_product_1`
    FOREIGN KEY (`affilate_product_id`)
    REFERENCES `flight`.`product` (`product_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `flight`.`aircraft`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `flight`.`aircraft` ;

CREATE TABLE IF NOT EXISTS `flight`.`aircraft` (
  `aircraft_id` INT NOT NULL,
  `aircraft_code` VARCHAR(10) NOT NULL,
  `aircraft_model` VARCHAR(10) NOT NULL,
  `aircraft_payload` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`aircraft_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `flight`.`airline`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `flight`.`airline` ;

CREATE TABLE IF NOT EXISTS `flight`.`airline` (
  `airline_id` INT NOT NULL,
  `airline_name` VARCHAR(45) NOT NULL,
  `airline_code` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`airline_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `flight`.`airline_ticket`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `flight`.`airline_ticket` ;

CREATE TABLE IF NOT EXISTS `flight`.`airline_ticket` (
  `airline_ticket_id` INT NOT NULL,
  PRIMARY KEY (`airline_ticket_id`),
  CONSTRAINT `FK_product_TO_airline_ticket_1`
    FOREIGN KEY (`airline_ticket_id`)
    REFERENCES `flight`.`product` (`product_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `flight`.`combined_product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `flight`.`combined_product` ;

CREATE TABLE IF NOT EXISTS `flight`.`combined_product` (
  `combined_product_id` INT NOT NULL,
  PRIMARY KEY (`combined_product_id`),
  CONSTRAINT `FK_product_TO_combined_product_1`
    FOREIGN KEY (`combined_product_id`)
    REFERENCES `flight`.`product` (`product_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `flight`.`extra_service_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `flight`.`extra_service_type` ;

CREATE TABLE IF NOT EXISTS `flight`.`extra_service_type` (
  `extra_type_id` INT NOT NULL,
  `extra_type_value` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`extra_type_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `flight`.`extra_service`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `flight`.`extra_service` ;

CREATE TABLE IF NOT EXISTS `flight`.`extra_service` (
  `extra_service_id` INT NOT NULL,
  `extra_type_id` INT NOT NULL,
  PRIMARY KEY (`extra_service_id`),
  INDEX `FK_extra_service_type_TO_extra_service_1` (`extra_type_id` ASC) VISIBLE,
  CONSTRAINT `FK_extra_service_type_TO_extra_service_1`
    FOREIGN KEY (`extra_type_id`)
    REFERENCES `flight`.`extra_service_type` (`extra_type_id`),
  CONSTRAINT `FK_product_TO_extra_service_1`
    FOREIGN KEY (`extra_service_id`)
    REFERENCES `flight`.`product` (`product_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `flight`.`combined_product_detail`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `flight`.`combined_product_detail` ;

CREATE TABLE IF NOT EXISTS `flight`.`combined_product_detail` (
  `combined_product_detail_id` INT NOT NULL,
  `combined_product_id` INT NOT NULL,
  `airline_ticket_id` INT NULL,
  `extra_service_id` INT NULL,
  `affilate_product_id` INT NULL,
  `accessory_id` INT NULL,
  PRIMARY KEY (`combined_product_id`, `combined_product_detail_id`),
  INDEX `FK_airline_ticket_TO_combined_product_detail_1` (`airline_ticket_id` ASC) VISIBLE,
  INDEX `FK_extra_service_TO_combined_product_detail_1` (`extra_service_id` ASC) VISIBLE,
  INDEX `FK_affilate_product_TO_combined_product_detail_1` (`affilate_product_id` ASC) VISIBLE,
  INDEX `FK_accessory_TO_combined_product_detail_1` (`accessory_id` ASC) VISIBLE,
  CONSTRAINT `FK_accessory_TO_combined_product_detail_1`
    FOREIGN KEY (`accessory_id`)
    REFERENCES `flight`.`accessory` (`accessory_id`),
  CONSTRAINT `FK_affilate_product_TO_combined_product_detail_1`
    FOREIGN KEY (`affilate_product_id`)
    REFERENCES `flight`.`affilate_product` (`affilate_product_id`),
  CONSTRAINT `FK_airline_ticket_TO_combined_product_detail_1`
    FOREIGN KEY (`airline_ticket_id`)
    REFERENCES `flight`.`airline_ticket` (`airline_ticket_id`),
  CONSTRAINT `FK_combined_product_TO_combined_product_detail_1`
    FOREIGN KEY (`combined_product_id`)
    REFERENCES `flight`.`combined_product` (`combined_product_id`),
  CONSTRAINT `FK_extra_service_TO_combined_product_detail_1`
    FOREIGN KEY (`extra_service_id`)
    REFERENCES `flight`.`extra_service` (`extra_service_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `flight`.`corporation_customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `flight`.`corporation_customer` ;

CREATE TABLE IF NOT EXISTS `flight`.`corporation_customer` (
  `customer_no` INT NOT NULL,
  `represent_name` VARCHAR(45) NOT NULL,
  `company_registration_no` VARCHAR(45) NOT NULL,
  `company_code` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`customer_no`),
  CONSTRAINT `FK_customer_TO_corporation_customer_1`
    FOREIGN KEY (`customer_no`)
    REFERENCES `flight`.`customer` (`customer_no`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `flight`.`corporation_benefit`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `flight`.`corporation_benefit` ;

CREATE TABLE IF NOT EXISTS `flight`.`corporation_benefit` (
  `benefit_id` INT NOT NULL,
  `coporation_benefit_value` VARCHAR(45) NOT NULL,
  `customer_no` INT NOT NULL,
  PRIMARY KEY (`benefit_id`),
  INDEX `FK_corporation_customer_TO_corporation_benefit_1` (`customer_no` ASC) VISIBLE,
  CONSTRAINT `FK_corporation_customer_TO_corporation_benefit_1`
    FOREIGN KEY (`customer_no`)
    REFERENCES `flight`.`corporation_customer` (`customer_no`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `flight`.`individual_customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `flight`.`individual_customer` ;

CREATE TABLE IF NOT EXISTS `flight`.`individual_customer` (
  `customer_no` INT NOT NULL,
  PRIMARY KEY (`customer_no`),
  CONSTRAINT `FK_customer_TO_individual_customer_1`
    FOREIGN KEY (`customer_no`)
    REFERENCES `flight`.`customer` (`customer_no`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `flight`.`corporation_customer_employee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `flight`.`corporation_customer_employee` ;

CREATE TABLE IF NOT EXISTS `flight`.`corporation_customer_employee` (
  `customer_no` INT NOT NULL,
  `corporation_customer_no` INT NOT NULL,
  PRIMARY KEY (`customer_no`, `corporation_customer_no`),
  INDEX `FK_corporation_customer_TO_corporation_customer_employee_1` (`corporation_customer_no` ASC) VISIBLE,
  CONSTRAINT `FK_corporation_customer_TO_corporation_customer_employee_1`
    FOREIGN KEY (`corporation_customer_no`)
    REFERENCES `flight`.`corporation_customer` (`customer_no`),
  CONSTRAINT `FK_individual_customer_TO_corporation_customer_employee_1`
    FOREIGN KEY (`customer_no`)
    REFERENCES `flight`.`individual_customer` (`customer_no`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `flight`.`coupon`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `flight`.`coupon` ;

CREATE TABLE IF NOT EXISTS `flight`.`coupon` (
  `coupon_id` INT NOT NULL,
  `SEG_id` INT NOT NULL,
  `PNR_id` INT NOT NULL,
  PRIMARY KEY (`coupon_id`, `SEG_id`, `PNR_id`),
  INDEX `FK_SEG_TO_coupon_1` (`SEG_id` ASC) VISIBLE,
  INDEX `FK_SEG_TO_coupon_2` (`PNR_id` ASC) VISIBLE,
  CONSTRAINT `FK_SEG_TO_coupon_1`
    FOREIGN KEY (`SEG_id`)
    REFERENCES `flight`.`SEG` (`SEG_id`),
  CONSTRAINT `FK_SEG_TO_coupon_2`
    FOREIGN KEY (`PNR_id`)
    REFERENCES `flight`.`SEG` (`PNR_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `flight`.`crew_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `flight`.`crew_type` ;

CREATE TABLE IF NOT EXISTS `flight`.`crew_type` (
  `crew_type_id` INT NOT NULL,
  `crew_type_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`crew_type_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `flight`.`crew`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `flight`.`crew` ;

CREATE TABLE IF NOT EXISTS `flight`.`crew` (
  `crew_id` INT NOT NULL,
  `crew_name` VARCHAR(45) NOT NULL,
  `crew_type_id` INT NOT NULL,
  PRIMARY KEY (`crew_id`),
  INDEX `FK_crew_type_TO_crew_1` (`crew_type_id` ASC) VISIBLE,
  CONSTRAINT `FK_crew_type_TO_crew_1`
    FOREIGN KEY (`crew_type_id`)
    REFERENCES `flight`.`crew_type` (`crew_type_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `flight`.`crew_flight_plan`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `flight`.`crew_flight_plan` ;

CREATE TABLE IF NOT EXISTS `flight`.`crew_flight_plan` (
  `crew_flight_plan_id` INT NOT NULL,
  `crew_flight_plan_value` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`crew_flight_plan_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `flight`.`crew_organization`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `flight`.`crew_organization` ;

CREATE TABLE IF NOT EXISTS `flight`.`crew_organization` (
  `cavin_crew_id` INT NOT NULL,
  `crew_id` INT NOT NULL,
  `crew_flight_plan_id` INT NOT NULL,
  PRIMARY KEY (`cavin_crew_id`, `crew_id`, `crew_flight_plan_id`),
  INDEX `FK_crew_TO_crew_organization_1` (`crew_id` ASC) VISIBLE,
  INDEX `FK_crew_flight_plan_TO_crew_organization_1` (`crew_flight_plan_id` ASC) VISIBLE,
  CONSTRAINT `FK_crew_flight_plan_TO_crew_organization_1`
    FOREIGN KEY (`crew_flight_plan_id`)
    REFERENCES `flight`.`crew_flight_plan` (`crew_flight_plan_id`),
  CONSTRAINT `FK_crew_TO_crew_organization_1`
    FOREIGN KEY (`crew_id`)
    REFERENCES `flight`.`crew` (`crew_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `flight`.`customer_identification`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `flight`.`customer_identification` ;

CREATE TABLE IF NOT EXISTS `flight`.`customer_identification` (
  `customer_no` INT NOT NULL,
  `passport` VARCHAR(45) NOT NULL,
  `registration_card` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`customer_no`),
  CONSTRAINT `FK_customer_TO_customer_identification_1`
    FOREIGN KEY (`customer_no`)
    REFERENCES `flight`.`customer` (`customer_no`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `flight`.`flight_path`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `flight`.`flight_path` ;

CREATE TABLE IF NOT EXISTS `flight`.`flight_path` (
  `flight_path_id` INT NOT NULL,
  `flight_path_name` VARCHAR(200) NOT NULL,
  `departure_airport_id` INT NOT NULL,
  `arrival_airport_id` INT NOT NULL,
  PRIMARY KEY (`flight_path_id`),
  INDEX `FK_airport_TO_flight_path_1` (`departure_airport_id` ASC) VISIBLE,
  INDEX `FK_airport_TO_flight_path_2` (`arrival_airport_id` ASC) VISIBLE,
  CONSTRAINT `FK_airport_TO_flight_path_1`
    FOREIGN KEY (`departure_airport_id`)
    REFERENCES `flight`.`airport` (`airport_id`),
  CONSTRAINT `FK_airport_TO_flight_path_2`
    FOREIGN KEY (`arrival_airport_id`)
    REFERENCES `flight`.`airport` (`airport_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `flight`.`departure_arrival`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `flight`.`departure_arrival` ;

CREATE TABLE IF NOT EXISTS `flight`.`departure_arrival` (
  `flight_path_id` INT NOT NULL,
  `Mileage` INT NOT NULL,
  INDEX `FK_flight_path_TO_departure_arrival_1` (`flight_path_id` ASC) VISIBLE,
  CONSTRAINT `FK_flight_path_TO_departure_arrival_1`
    FOREIGN KEY (`flight_path_id`)
    REFERENCES `flight`.`flight_path` (`flight_path_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `flight`.`extra_service_reserved`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `flight`.`extra_service_reserved` ;

CREATE TABLE IF NOT EXISTS `flight`.`extra_service_reserved` (
  `extra_service_id` INT NOT NULL,
  `SEG_id` INT NOT NULL,
  `PAX_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  PRIMARY KEY (`extra_service_id`, `SEG_id`, `PAX_id`, `product_id`),
  INDEX `FK_SEG_TO_extra_service_reserved_1` (`SEG_id` ASC) VISIBLE,
  INDEX `FK_PAX_TO_extra_service_reserved_1` (`PAX_id` ASC) VISIBLE,
  INDEX `FK_product_TO_extra_service_reserved_1` (`product_id` ASC) VISIBLE,
  CONSTRAINT `FK_PAX_TO_extra_service_reserved_1`
    FOREIGN KEY (`PAX_id`)
    REFERENCES `flight`.`PAX` (`PAX_id`),
  CONSTRAINT `FK_product_TO_extra_service_reserved_1`
    FOREIGN KEY (`product_id`)
    REFERENCES `flight`.`product` (`product_id`),
  CONSTRAINT `FK_SEG_TO_extra_service_reserved_1`
    FOREIGN KEY (`SEG_id`)
    REFERENCES `flight`.`SEG` (`SEG_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `flight`.`flight_plan`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `flight`.`flight_plan` ;

CREATE TABLE IF NOT EXISTS `flight`.`flight_plan` (
  `flight_plan_id` INT NOT NULL,
  `aircraft_key` INT NOT NULL,
  `flight_path_id` INT NOT NULL,
  `departure_time` DATETIME NOT NULL,
  `arrival_time` DATETIME NOT NULL,
  `season_code` VARCHAR(45) NOT NULL,
  `crew_flight_plan_id` INT NOT NULL,
  `airline_id` INT NOT NULL,
  `flight_plan_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`flight_plan_id`),
  INDEX `FK_aircraft_TO_flight_plan_1` (`aircraft_key` ASC) VISIBLE,
  INDEX `FK_flight_path_TO_flight_plan_1` (`flight_path_id` ASC) VISIBLE,
  INDEX `FK_crew_flight_plan_TO_flight_plan_1` (`crew_flight_plan_id` ASC) VISIBLE,
  INDEX `FK_airline_TO_flight_plan_1` (`airline_id` ASC) VISIBLE,
  CONSTRAINT `FK_aircraft_TO_flight_plan_1`
    FOREIGN KEY (`aircraft_key`)
    REFERENCES `flight`.`aircraft` (`aircraft_id`),
  CONSTRAINT `FK_airline_TO_flight_plan_1`
    FOREIGN KEY (`airline_id`)
    REFERENCES `flight`.`airline` (`airline_id`),
  CONSTRAINT `FK_crew_flight_plan_TO_flight_plan_1`
    FOREIGN KEY (`crew_flight_plan_id`)
    REFERENCES `flight`.`crew_flight_plan` (`crew_flight_plan_id`),
  CONSTRAINT `FK_flight_path_TO_flight_plan_1`
    FOREIGN KEY (`flight_path_id`)
    REFERENCES `flight`.`flight_path` (`flight_path_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `flight`.`full_member`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `flight`.`full_member` ;

CREATE TABLE IF NOT EXISTS `flight`.`full_member` (
  `customer_no` INT NOT NULL,
  `id` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`customer_no`),
  CONSTRAINT `FK_individual_customer_TO_full_member_1`
    FOREIGN KEY (`customer_no`)
    REFERENCES `flight`.`individual_customer` (`customer_no`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `flight`.`refund_fare`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `flight`.`refund_fare` ;

CREATE TABLE IF NOT EXISTS `flight`.`refund_fare` (
  `PAX_id` INT NOT NULL,
  `PNR_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `refund_fare_name` VARCHAR(45) NOT NULL,
  `refund_fare_price` INT NOT NULL,
  PRIMARY KEY (`PAX_id`, `PNR_id`, `product_id`),
  CONSTRAINT `fk_refund_fare_refund1`
    FOREIGN KEY (`PAX_id` , `PNR_id` , `product_id`)
    REFERENCES `flight`.`refund` (`PAX_id` , `PNR_id` , `product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `flight`.`runway`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `flight`.`runway` ;

CREATE TABLE IF NOT EXISTS `flight`.`runway` (
  `id` VARCHAR(5) NOT NULL,
  `length` VARCHAR(30) NOT NULL,
  `taxiway_count` INT NOT NULL,
  `airport_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_airport_TO_runway_1` (`airport_id` ASC) VISIBLE,
  CONSTRAINT `FK_airport_TO_runway_1`
    FOREIGN KEY (`airport_id`)
    REFERENCES `flight`.`airport` (`airport_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `flight`.`seat_grade`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `flight`.`seat_grade` ;

CREATE TABLE IF NOT EXISTS `flight`.`seat_grade` (
  `seat_grade_id` INT NOT NULL,
  `seat_grade_name` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`seat_grade_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `flight`.`seat`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `flight`.`seat` ;

CREATE TABLE IF NOT EXISTS `flight`.`seat` (
  `seat_id` INT NOT NULL,
  `seat_name` VARCHAR(10) NOT NULL,
  `seat_grade_id` INT NOT NULL,
  `aircraft_id` INT NOT NULL,
  PRIMARY KEY (`seat_id`),
  INDEX `FK_seat_grade_TO_seat_1` (`seat_grade_id` ASC) VISIBLE,
  INDEX `FK_aircraft_TO_seat_1` (`aircraft_id` ASC) VISIBLE,
  CONSTRAINT `FK_aircraft_TO_seat_1`
    FOREIGN KEY (`aircraft_id`)
    REFERENCES `flight`.`aircraft` (`aircraft_id`),
  CONSTRAINT `FK_seat_grade_TO_seat_1`
    FOREIGN KEY (`seat_grade_id`)
    REFERENCES `flight`.`seat_grade` (`seat_grade_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `flight`.`seat_count`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `flight`.`seat_count` ;

CREATE TABLE IF NOT EXISTS `flight`.`seat_count` (
  `flight_plan_id` INT NOT NULL,
  `seat_grade_id` INT NOT NULL,
  `seat_count` INT NOT NULL,
  `product_id` INT NOT NULL,
  PRIMARY KEY (`flight_plan_id`, `seat_grade_id`),
  INDEX `fk_seat_count_product1_idx` (`product_id` ASC) VISIBLE,
  INDEX `fk_seat_count_flight_plan1_idx` (`flight_plan_id` ASC) VISIBLE,
  CONSTRAINT `fk_seat_count_seat_grade1`
    FOREIGN KEY (`seat_grade_id`)
    REFERENCES `flight`.`seat_grade` (`seat_grade_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_seat_count_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `flight`.`product` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_seat_count_flight_plan1`
    FOREIGN KEY (`flight_plan_id`)
    REFERENCES `flight`.`flight_plan` (`flight_plan_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `flight`.`simple_member_company_info`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `flight`.`simple_member_company_info` ;

CREATE TABLE IF NOT EXISTS `flight`.`simple_member_company_info` (
  `company_info_id` INT NOT NULL,
  `company_info_value` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`company_info_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `flight`.`simple_member`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `flight`.`simple_member` ;

CREATE TABLE IF NOT EXISTS `flight`.`simple_member` (
  `customer_no` INT NOT NULL,
  `company_id` INT NOT NULL,
  PRIMARY KEY (`customer_no`),
  INDEX `FK_simple_member_company_info_TO_simple_member_1` (`company_id` ASC) VISIBLE,
  CONSTRAINT `FK_individual_customer_TO_simple_member_1`
    FOREIGN KEY (`customer_no`)
    REFERENCES `flight`.`individual_customer` (`customer_no`),
  CONSTRAINT `FK_simple_member_company_info_TO_simple_member_1`
    FOREIGN KEY (`company_id`)
    REFERENCES `flight`.`simple_member_company_info` (`company_info_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `flight`.`favorite`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `flight`.`favorite` ;

CREATE TABLE IF NOT EXISTS `flight`.`favorite` (
  `customer_no` INT NOT NULL,
  INDEX `fk_favorite_customer1_idx` (`customer_no` ASC) VISIBLE,
  CONSTRAINT `fk_favorite_customer1`
    FOREIGN KEY (`customer_no`)
    REFERENCES `flight`.`customer` (`customer_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `flight`.`ticket`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `flight`.`ticket` ;

CREATE TABLE IF NOT EXISTS `flight`.`ticket` (
  `PAX_id` INT NOT NULL,
  `PNR_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  PRIMARY KEY (`PAX_id`, `PNR_id`, `product_id`),
  INDEX `fk_ticket_product1_idx` (`product_id` ASC) VISIBLE,
  CONSTRAINT `fk_ticket_PAX1`
    FOREIGN KEY (`PAX_id` , `PNR_id`)
    REFERENCES `flight`.`PAX` (`PAX_id` , `PNR_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ticket_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `flight`.`product` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `flight`.`refund`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `flight`.`refund` ;

CREATE TABLE IF NOT EXISTS `flight`.`refund` (
  `PAX_id` INT NOT NULL,
  `PNR_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  PRIMARY KEY (`PAX_id`, `PNR_id`, `product_id`),
  CONSTRAINT `fk_refund_ticket2`
    FOREIGN KEY (`PAX_id` , `PNR_id` , `product_id`)
    REFERENCES `flight`.`ticket` (`PAX_id` , `PNR_id` , `product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `flight`.`payment_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `flight`.`payment_type` ;

CREATE TABLE IF NOT EXISTS `flight`.`payment_type` (
  `payment_type_id` INT NOT NULL,
  `payment_type_value` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`payment_type_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `flight`.`payment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `flight`.`payment` ;

CREATE TABLE IF NOT EXISTS `flight`.`payment` (
  `PAX_id` INT NOT NULL,
  `PNR_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `payment_type_id` INT NOT NULL,
  `payment_approval_no` VARCHAR(45) NOT NULL,
  `payment_date` DATE NOT NULL,
  `payment_price` INT NOT NULL,
  PRIMARY KEY (`PAX_id`, `PNR_id`, `product_id`),
  INDEX `fk_payment_payment_type2_idx` (`payment_type_id` ASC) VISIBLE,
  CONSTRAINT `fk_payment_ticket2`
    FOREIGN KEY (`PAX_id` , `PNR_id` , `product_id`)
    REFERENCES `flight`.`ticket` (`PAX_id` , `PNR_id` , `product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_payment_payment_type2`
    FOREIGN KEY (`payment_type_id`)
    REFERENCES `flight`.`payment_type` (`payment_type_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `flight`.`refund_payment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `flight`.`refund_payment` ;

CREATE TABLE IF NOT EXISTS `flight`.`refund_payment` (
  `PAX_id` INT NOT NULL,
  `PNR_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `payment_type_id` INT NOT NULL,
  PRIMARY KEY (`PAX_id`, `PNR_id`, `product_id`),
  INDEX `fk_refund_payment_payment_type2_idx` (`payment_type_id` ASC) VISIBLE,
  CONSTRAINT `fk_refund_payment_refund2`
    FOREIGN KEY (`PAX_id` , `PNR_id` , `product_id`)
    REFERENCES `flight`.`refund` (`PAX_id` , `PNR_id` , `product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_refund_payment_payment_type2`
    FOREIGN KEY (`payment_type_id`)
    REFERENCES `flight`.`payment_type` (`payment_type_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `flight`.`tax_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `flight`.`tax_type` ;

CREATE TABLE IF NOT EXISTS `flight`.`tax_type` (
  `tax_id` INT NOT NULL,
  `tax_type_value` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`tax_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `flight`.`tax`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `flight`.`tax` ;

CREATE TABLE IF NOT EXISTS `flight`.`tax` (
  `PAX_id` INT NOT NULL,
  `PNR_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `tax_type_id` INT NOT NULL,
  `tax` INT NOT NULL,
  PRIMARY KEY (`PAX_id`, `PNR_id`, `product_id`),
  INDEX `fk_tax_tax_type1_idx` (`tax_type_id` ASC) VISIBLE,
  CONSTRAINT `fk_tax_ticket2`
    FOREIGN KEY (`PAX_id` , `PNR_id` , `product_id`)
    REFERENCES `flight`.`ticket` (`PAX_id` , `PNR_id` , `product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tax_tax_type1`
    FOREIGN KEY (`tax_type_id`)
    REFERENCES `flight`.`tax_type` (`tax_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `flight`.`refund_tax`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `flight`.`refund_tax` ;

CREATE TABLE IF NOT EXISTS `flight`.`refund_tax` (
  `PAX_id` INT NOT NULL,
  `PNR_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `tax_type_id` INT NOT NULL,
  `tax` INT NOT NULL,
  PRIMARY KEY (`PAX_id`, `PNR_id`, `product_id`),
  INDEX `fk_refund_tax_tax_type2_idx` (`tax_type_id` ASC) VISIBLE,
  CONSTRAINT `fk_refund_tax_refund2`
    FOREIGN KEY (`PAX_id` , `PNR_id` , `product_id`)
    REFERENCES `flight`.`refund` (`PAX_id` , `PNR_id` , `product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_refund_tax_tax_type2`
    FOREIGN KEY (`tax_type_id`)
    REFERENCES `flight`.`tax_type` (`tax_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `flight`.`fare`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `flight`.`fare` ;

CREATE TABLE IF NOT EXISTS `flight`.`fare` (
  `PAX_id` INT NOT NULL,
  `PNR_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `fare_name` VARCHAR(45) NOT NULL,
  `fare_price` INT NOT NULL,
  PRIMARY KEY (`PAX_id`, `PNR_id`, `product_id`),
  CONSTRAINT `fk_fare_ticket2`
    FOREIGN KEY (`PAX_id` , `PNR_id` , `product_id`)
    REFERENCES `flight`.`ticket` (`PAX_id` , `PNR_id` , `product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `flight`.`refund_fare`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `flight`.`refund_fare` ;

CREATE TABLE IF NOT EXISTS `flight`.`refund_fare` (
  `PAX_id` INT NOT NULL,
  `PNR_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `refund_fare_name` VARCHAR(45) NOT NULL,
  `refund_fare_price` INT NOT NULL,
  PRIMARY KEY (`PAX_id`, `PNR_id`, `product_id`),
  CONSTRAINT `fk_refund_fare_refund1`
    FOREIGN KEY (`PAX_id` , `PNR_id` , `product_id`)
    REFERENCES `flight`.`refund` (`PAX_id` , `PNR_id` , `product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
