-- MySQL Script generated by MySQL Workbench
-- Thu Apr 27 10:48:40 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`user` ;

CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `user_id` INT NOT NULL,
  `id` VARCHAR(20) NOT NULL,
  `password` VARCHAR(20) NOT NULL,
  `phone_number` VARCHAR(20) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`image`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`image` ;

CREATE TABLE IF NOT EXISTS `mydb`.`image` (
  `image_id` INT NOT NULL,
  `image_url` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`image_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`profile`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`profile` ;

CREATE TABLE IF NOT EXISTS `mydb`.`profile` (
  `user_user_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `mail_received_agreement` TINYINT NOT NULL,
  `event_received_agreement` TINYINT NOT NULL,
  `image_image_id` INT NOT NULL,
  `b_point` INT NULL DEFAULT NULL,
  PRIMARY KEY (`user_user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`my_buddy`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`my_buddy` ;

CREATE TABLE IF NOT EXISTS `mydb`.`my_buddy` (
  `buddy_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `type` ENUM('dog', 'cat') NOT NULL,
  `gender` ENUM('M', 'F') NOT NULL,
  `image_id` INT NOT NULL,
  PRIMARY KEY (`buddy_id`, `user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`body_info`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`body_info` ;

CREATE TABLE IF NOT EXISTS `mydb`.`body_info` (
  `my_buddy_id` INT NOT NULL,
  `Neck_round` INT NULL DEFAULT NULL,
  `chest_round` INT NULL DEFAULT NULL,
  `back_length` INT NULL DEFAULT NULL,
  `leg_length` INT NULL DEFAULT NULL,
  `weight` INT NULL DEFAULT NULL,
  PRIMARY KEY (`my_buddy_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`disease`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`disease` ;

CREATE TABLE IF NOT EXISTS `mydb`.`disease` (
  `disease_code` INT NOT NULL,
  `disease_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`disease_code`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`disease_buddy`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`disease_buddy` ;

CREATE TABLE IF NOT EXISTS `mydb`.`disease_buddy` (
  `disease_code` INT NOT NULL,
  `buddy_id` INT NOT NULL,
  PRIMARY KEY (`disease_code`, `buddy_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`allergy`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`allergy` ;

CREATE TABLE IF NOT EXISTS `mydb`.`allergy` (
  `allergy_code` INT NOT NULL,
  `allergy_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`allergy_code`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`allergy_buddy`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`allergy_buddy` ;

CREATE TABLE IF NOT EXISTS `mydb`.`allergy_buddy` (
  `allergy_allergy_code` INT NOT NULL,
  `my_buddy_buddy_id` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`allergy_allergy_code`, `my_buddy_buddy_id`),
  INDEX `fk_allergy_has_my_buddy_allergy1_idx` (`allergy_allergy_code` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`category` ;

CREATE TABLE IF NOT EXISTS `mydb`.`category` (
  `category_id` INT NOT NULL,
  `category_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`category_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`sub_category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`sub_category` ;

CREATE TABLE IF NOT EXISTS `mydb`.`sub_category` (
  `sub_category_id` INT NOT NULL,
  `sub_category_name` VARCHAR(45) NOT NULL,
  `category_id` INT NOT NULL,
  PRIMARY KEY (`sub_category_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`brand`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`brand` ;

CREATE TABLE IF NOT EXISTS `mydb`.`brand` (
  `brand_id` INT NOT NULL,
  `brand_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`brand_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`event`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`event` ;

CREATE TABLE IF NOT EXISTS `mydb`.`event` (
  `event_id` INT NOT NULL,
  `event_name` VARCHAR(45) NOT NULL,
  `image_image_id` INT NOT NULL,
  `start_date` DATETIME NULL DEFAULT NULL,
  `end_date` DATETIME NULL DEFAULT NULL,
  `discount_price` INT NULL DEFAULT NULL,
  `option` ENUM('percent', 'won') NULL DEFAULT NULL,
  PRIMARY KEY (`event_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`product` ;

CREATE TABLE IF NOT EXISTS `mydb`.`product` (
  `product_id` INT NOT NULL,
  `product_price` VARCHAR(45) NOT NULL,
  `product_name` VARCHAR(45) NOT NULL,
  `sub_category_id` INT NOT NULL,
  `brand_id` INT NOT NULL,
  `event_id` INT NOT NULL,
  `bien_delivery` TINYINT(1) NOT NULL,
  `sub_category_id` INT NOT NULL,
  PRIMARY KEY (`product_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`and_you_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`and_you_type` ;

CREATE TABLE IF NOT EXISTS `mydb`.`and_you_type` (
  `type_code` INT NOT NULL,
  `type_name` VARCHAR(45) NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`type_code`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`and_you`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`and_you` ;

CREATE TABLE IF NOT EXISTS `mydb`.`and_you` (
  `and_you_id` INT NOT NULL,
  `and_you_type_type_code` INT NOT NULL,
  PRIMARY KEY (`and_you_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`option`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`option` ;

CREATE TABLE IF NOT EXISTS `mydb`.`option` (
  `option_id` INT NOT NULL,
  `option_name` VARCHAR(45) NOT NULL,
  `product_product_id` INT NOT NULL,
  PRIMARY KEY (`option_id`, `product_product_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`option_value`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`option_value` ;

CREATE TABLE IF NOT EXISTS `mydb`.`option_value` (
  `option_value_id` INT NOT NULL,
  `option_value_name` VARCHAR(45) NOT NULL,
  `addtional_fee` INT NOT NULL,
  `option_id` INT NOT NULL,
  PRIMARY KEY (`option_value_id`, `option_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`and_you_has_image`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`and_you_has_image` ;

CREATE TABLE IF NOT EXISTS `mydb`.`and_you_has_image` (
  `and_you_and_you_id` INT NOT NULL,
  `image_image_id` INT NOT NULL,
  PRIMARY KEY (`and_you_and_you_id`, `image_image_id`),
  INDEX `fk_and_you_has_image_and_you1_idx` (`and_you_and_you_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`comment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`comment` ;

CREATE TABLE IF NOT EXISTS `mydb`.`comment` (
  `comment_id` INT NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  `content` TEXT NOT NULL,
  `parent_comment_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `user_user_id` INT NOT NULL,
  `star_grade` INT NULL DEFAULT NULL,
  PRIMARY KEY (`comment_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`wishlist`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`wishlist` ;

CREATE TABLE IF NOT EXISTS `mydb`.`wishlist` (
  `user_user_id` INT NOT NULL,
  `product_product_id` INT NOT NULL,
  `product_count` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`user_user_id`, `product_product_id`),
  INDEX `fk_user_has_product_user1_idx` (`user_user_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cart`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`cart` ;

CREATE TABLE IF NOT EXISTS `mydb`.`cart` (
  `cart_id` INT NOT NULL,
  `product_count` INT NOT NULL,
  `user_id` INT NOT NULL,
  `product_product_id` INT NOT NULL,
  PRIMARY KEY (`cart_id`, `user_id`, `product_product_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`order` ;

CREATE TABLE IF NOT EXISTS `mydb`.`order` (
  `order_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `receiver_name` VARCHAR(45) NOT NULL,
  `receiver_phone` VARCHAR(20) NOT NULL,
  `order_date` DATETIME NOT NULL,
  `discount_price` INT NULL DEFAULT NULL,
  PRIMARY KEY (`order_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`order_detail`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`order_detail` ;

CREATE TABLE IF NOT EXISTS `mydb`.`order_detail` (
  `order_detail_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `order_id` INT NOT NULL,
  `product_count` INT NOT NULL,
  `product_price` VARCHAR(45) NOT NULL,
  `order_detail_status` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`order_detail_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`deliver_address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`deliver_address` ;

CREATE TABLE IF NOT EXISTS `mydb`.`deliver_address` (
  `user_id` INT NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`coupon`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`coupon` ;

CREATE TABLE IF NOT EXISTS `mydb`.`coupon` (
  `coupon_id` INT NOT NULL,
  `coupon_option` ENUM('percent', 'won') NOT NULL,
  `coupon_name` VARCHAR(45) NOT NULL,
  `coupon_value` INT NULL DEFAULT NULL,
  `coupon_expiration_date` DATETIME NOT NULL,
  `min_price` INT NOT NULL,
  `duplication` TINYINT(1) NOT NULL,
  PRIMARY KEY (`coupon_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user_has_coupon`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`user_has_coupon` ;

CREATE TABLE IF NOT EXISTS `mydb`.`user_has_coupon` (
  `user_user_id` INT NOT NULL,
  `coupon_coupon_id` INT NOT NULL,
  PRIMARY KEY (`user_user_id`, `coupon_coupon_id`),
  INDEX `fk_user_has_coupon_user1_idx` (`user_user_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`inquiry`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`inquiry` ;

CREATE TABLE IF NOT EXISTS `mydb`.`inquiry` (
  `inquiry_id` INT NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  `content` TEXT NOT NULL,
  `parent_inquiry_id` INT NOT NULL,
  `product_product_id` INT NOT NULL,
  `user_user_id` INT NOT NULL,
  PRIMARY KEY (`inquiry_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`product_has_image`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`product_has_image` ;

CREATE TABLE IF NOT EXISTS `mydb`.`product_has_image` (
  `product_product_id` INT NOT NULL,
  `image_image_id` INT NOT NULL,
  PRIMARY KEY (`product_product_id`, `image_image_id`),
  INDEX `fk_product_has_image_product1_idx` (`product_product_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`comment_has_image`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`comment_has_image` ;

CREATE TABLE IF NOT EXISTS `mydb`.`comment_has_image` (
  `comment_comment_id` INT NOT NULL,
  `image_image_id` INT NOT NULL,
  PRIMARY KEY (`comment_comment_id`, `image_image_id`),
  INDEX `fk_comment_has_image_comment1_idx` (`comment_comment_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`faq_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`faq_type` ;

CREATE TABLE IF NOT EXISTS `mydb`.`faq_type` (
  `faq_type_id` INT NOT NULL,
  `faq_type_name` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`faq_type_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`faq`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`faq` ;

CREATE TABLE IF NOT EXISTS `mydb`.`faq` (
  `faq_id` INT NOT NULL,
  `title` VARCHAR(45) NULL DEFAULT NULL,
  `question` VARCHAR(45) NULL DEFAULT NULL,
  `answer` TEXT NULL DEFAULT NULL,
  `faq_type_id` INT NOT NULL,
  PRIMARY KEY (`faq_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
