### 가족관계 등록

POST localhost:8080/residents/1/relationship
Content-Type: application/json

{
    "familySerialNumber": 7,
    "relationShip": "father"
}

### 가족관계 수정

PUT localhost:8080/residents/1/relationship/7
Content-Type: application/json

{
    "relationShip": "mother"
}

### 가족관계 삭제

DELETE localhost:8080/residents/1/relationship/7
Content-Type: application/json

