-- MySQL Script generated by MySQL Workbench
-- Wed Apr 26 10:43:28 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`building`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`building` (
  `building_id` INT NOT NULL,
  `building_name` VARCHAR(45) NULL,
  `building_location` VARCHAR(45) NULL,
  PRIMARY KEY (`building_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`room`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`room` (
  `room_id` INT NOT NULL,
  `location` VARCHAR(45) NULL,
  `building_id` INT NOT NULL,
  PRIMARY KEY (`room_id`),
  INDEX `fk_lecture_room_building1_idx` (`building_id` ASC) VISIBLE,
  CONSTRAINT `fk_lecture_room_building1`
    FOREIGN KEY (`building_id`)
    REFERENCES `mydb`.`building` (`building_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`department`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`department` (
  `department_id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `establishment_year` INT NULL,
  `room_room_id` INT NOT NULL,
  PRIMARY KEY (`department_id`, `room_room_id`),
  INDEX `fk_department_room1_idx` (`room_room_id` ASC) VISIBLE,
  CONSTRAINT `fk_department_room1`
    FOREIGN KEY (`room_room_id`)
    REFERENCES `mydb`.`room` (`room_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`major`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`major` (
  `major_id` INT NOT NULL,
  `major_name` VARCHAR(45) NULL,
  `department_department_id` INT NOT NULL,
  PRIMARY KEY (`major_id`),
  INDEX `fk_major_department1_idx` (`department_department_id` ASC) VISIBLE,
  CONSTRAINT `fk_major_department1`
    FOREIGN KEY (`department_department_id`)
    REFERENCES `mydb`.`department` (`department_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`city`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`city` (
  `city_id` INT NOT NULL,
  `city_name` VARCHAR(45) NULL,
  PRIMARY KEY (`city_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`person` (
  `person_id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `phone_number` VARCHAR(13) NULL,
  `gender` TINYINT NULL,
  `city_id` INT NOT NULL,
  PRIMARY KEY (`person_id`),
  INDEX `fk_person_city1_idx` (`city_id` ASC) VISIBLE,
  CONSTRAINT `fk_person_city1`
    FOREIGN KEY (`city_id`)
    REFERENCES `mydb`.`city` (`city_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`professor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`professor` (
  `professor_id` INT NOT NULL,
  `major_major_id` VARCHAR(45) NOT NULL,
  `person_person_id` INT NOT NULL,
  `room_room_id` INT NOT NULL,
  PRIMARY KEY (`professor_id`),
  INDEX `fk_professor_major1_idx` (`major_major_id` ASC) VISIBLE,
  INDEX `fk_professor_person1_idx` (`person_person_id` ASC) VISIBLE,
  INDEX `fk_professor_room1_idx` (`room_room_id` ASC) VISIBLE,
  CONSTRAINT `fk_professor_major1`
    FOREIGN KEY (`major_major_id`)
    REFERENCES `mydb`.`major` (`major_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_professor_person1`
    FOREIGN KEY (`person_person_id`)
    REFERENCES `mydb`.`person` (`person_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_professor_room1`
    FOREIGN KEY (`room_room_id`)
    REFERENCES `mydb`.`room` (`room_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`student` (
  `student_id` INT NOT NULL,
  `person_id` INT NOT NULL,
  `major_id` INT NOT NULL,
  `advisor_id` INT NOT NULL,
  `brith_year` INT NULL,
  PRIMARY KEY (`student_id`),
  INDEX `fk_student_professor1_idx` (`advisor_id` ASC) VISIBLE,
  INDEX `fk_student_major1_idx` (`major_id` ASC) VISIBLE,
  INDEX `fk_student_person2_idx` (`person_id` ASC) VISIBLE,
  CONSTRAINT `fk_student_professor1`
    FOREIGN KEY (`advisor_id`)
    REFERENCES `mydb`.`professor` (`professor_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_student_major1`
    FOREIGN KEY (`major_id`)
    REFERENCES `mydb`.`major` (`major_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_student_person2`
    FOREIGN KEY (`person_id`)
    REFERENCES `mydb`.`person` (`person_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`subject`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`subject` (
  `subject_id` INT NOT NULL,
  `subject_name` VARCHAR(45) NULL,
  PRIMARY KEY (`subject_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`lecture`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`lecture` (
  `lecture_id` INT NOT NULL,
  `subject_id` INT NOT NULL,
  `professor_id` INT NOT NULL,
  `lecture_time` DATETIME NULL,
  `room_room_id` INT NOT NULL,
  PRIMARY KEY (`lecture_id`),
  INDEX `fk_lecture_subject1_idx` (`subject_id` ASC) VISIBLE,
  INDEX `fk_lecture_professor1_idx` (`professor_id` ASC) VISIBLE,
  INDEX `fk_lecture_room1_idx` (`room_room_id` ASC) VISIBLE,
  CONSTRAINT `fk_lecture_subject1`
    FOREIGN KEY (`subject_id`)
    REFERENCES `mydb`.`subject` (`subject_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lecture_professor1`
    FOREIGN KEY (`professor_id`)
    REFERENCES `mydb`.`professor` (`professor_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lecture_room1`
    FOREIGN KEY (`room_room_id`)
    REFERENCES `mydb`.`room` (`room_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`grade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`grade` (
  `grade_id` INT NOT NULL,
  `grade_name` VARCHAR(2) NULL,
  `grade_score` FLOAT NULL,
  PRIMARY KEY (`grade_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`register`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`register` (
  `student_id` INT NOT NULL,
  `lecture_id` INT NOT NULL,
  `withdrawal` TINYINT NULL,
  `grade_id` INT NOT NULL,
  PRIMARY KEY (`student_id`, `lecture_id`),
  INDEX `fk_register_lecture1_idx` (`lecture_id` ASC) VISIBLE,
  INDEX `fk_register_grade1_idx` (`grade_id` ASC) VISIBLE,
  CONSTRAINT `fk_register_student1`
    FOREIGN KEY (`student_id`)
    REFERENCES `mydb`.`student` (`student_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_register_lecture1`
    FOREIGN KEY (`lecture_id`)
    REFERENCES `mydb`.`lecture` (`lecture_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_register_grade1`
    FOREIGN KEY (`grade_id`)
    REFERENCES `mydb`.`grade` (`grade_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`table1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`table1` (
  `lecture_room_id` INT NOT NULL,
  `lecture_lecture_id` INT NOT NULL,
  PRIMARY KEY (`lecture_room_id`, `lecture_lecture_id`),
  INDEX `fk_table1_lecture1_idx` (`lecture_lecture_id` ASC) VISIBLE,
  CONSTRAINT `fk_table1_lecture_room1`
    FOREIGN KEY (`lecture_room_id`)
    REFERENCES `mydb`.`room` (`room_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_table1_lecture1`
    FOREIGN KEY (`lecture_lecture_id`)
    REFERENCES `mydb`.`lecture` (`lecture_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`table2`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`table2` (
  `student_student_id` INT NOT NULL,
  PRIMARY KEY (`student_student_id`),
  CONSTRAINT `fk_table2_student1`
    FOREIGN KEY (`student_student_id`)
    REFERENCES `mydb`.`student` (`student_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`guardian`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`guardian` (
  `guardian_id` INT NOT NULL,
  `person_person_id` INT NOT NULL,
  `student_student_id` INT NOT NULL,
  PRIMARY KEY (`guardian_id`),
  INDEX `fk_guardian_person1_idx` (`person_person_id` ASC) VISIBLE,
  INDEX `fk_guardian_student1_idx` (`student_student_id` ASC) VISIBLE,
  CONSTRAINT `fk_guardian_person1`
    FOREIGN KEY (`person_person_id`)
    REFERENCES `mydb`.`person` (`person_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_guardian_student1`
    FOREIGN KEY (`student_student_id`)
    REFERENCES `mydb`.`student` (`student_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`person` (
  `person_id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `phone_number` VARCHAR(13) NULL,
  `gender` TINYINT NULL,
  `city_id` INT NOT NULL,
  PRIMARY KEY (`person_id`),
  INDEX `fk_person_city1_idx` (`city_id` ASC) VISIBLE,
  CONSTRAINT `fk_person_city1`
    FOREIGN KEY (`city_id`)
    REFERENCES `mydb`.`city` (`city_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`city`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`city` (
  `city_id` INT NOT NULL,
  `city_name` VARCHAR(45) NULL,
  PRIMARY KEY (`city_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`person_copy1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`person_copy1` (
  `person_id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `phone_number` VARCHAR(13) NULL,
  `email` VARCHAR(45) NULL,
  `gender` TINYINT NULL,
  `BirthYear` INT NULL,
  PRIMARY KEY (`person_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`table3`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`table3` (
  `city_id` INT NOT NULL,
  `city_name` VARCHAR(45) NULL,
  PRIMARY KEY (`city_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
